services:
  flask:
    build: .
    container_name: flask
    ports:
      - 5000:5000

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certificates:/etc/ssl:ro
    depends_on:
      - flask
    ports:
      - 443:443
